Jhon Glenn Fabul

Adolfo Cedric Sarillo

# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [1]:
pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
from numpy import random

#### 2. Print the numpy version

In [9]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [21]:
arr = np.array([0, 0, 0, 0, 0])
print(arr)
# double check

[0 0 0 0 0]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [16]:
arr = np.empty(15)
arr[6] = 1

print(arr)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [13]:
arr = np.arange(start=0, stop=16)
newarr = arr.reshape(4, 4)
print(newarr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [20]:
arr = np.array([1,2,4,0,4,0])
nonzero = np.where(arr != 0)
print(nonzero)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [29]:
x = random.rand(4,4,4)
print(x)

[[[0.58738628 0.30014796 0.08958102 0.92963157]
  [0.5096386  0.88585517 0.44501299 0.20717627]
  [0.60710157 0.36153628 0.3163283  0.51185733]
  [0.83086507 0.9467247  0.90854561 0.56695428]]

 [[0.43915658 0.24741374 0.65929379 0.07442731]
  [0.48144786 0.0841849  0.76364681 0.61284115]
  [0.15626888 0.80216651 0.49977458 0.73938108]
  [0.362083   0.1607964  0.54538099 0.47636731]]

 [[0.3458597  0.81550758 0.9789525  0.18802279]
  [0.8259505  0.12048502 0.94082648 0.9695973 ]
  [0.28009803 0.20062704 0.77610873 0.60294392]
  [0.63650349 0.28252156 0.45394645 0.47158386]]

 [[0.63158924 0.20996865 0.33450771 0.73759421]
  [0.94415093 0.84804469 0.20475672 0.96093984]
  [0.11974639 0.17570733 0.59326923 0.27250988]
  [0.47893308 0.30902165 0.18949002 0.94547375]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [189]:
arr = random.randint(1000, size=(15,15))
print(arr)

newarr = np.array(np.nditer(arr))
sortedarr = np.sort(newarr)
# print(sortedarr)
lowest = sortedarr[0]
highest = sortedarr[224]
print('')
print(f'Loweset: {lowest}')
print(f'Highest: {highest}')

[[740 907  20 654 209 829 920 322 177 579 378 200 916  51  55]
 [ 95 260 147  72 943 247 819 246 217 583 583 876 119 742 259]
 [789 541 770 417 993 499 710 591 779 791 893  80  26 822 219]
 [193 615 825 262 486 188 870 295 375 146 676 479  20 791 549]
 [ 64 713 130 359 607 286 231 552 970 636 113 388   9 839 579]
 [ 45 542 494 793 515 776 805 754 533 906 327 337  36 481 575]
 [949  89 474 120 790 246 314 496 787 652 976 151 169  55 639]
 [690 134 465  58 603 718 372 490 346 614 840 569 246 361  87]
 [230 213 438 362 400 794 387 612 198 178 802 773 218 460 764]
 [395 777 143 453  53 499 596 854 736 788 885 247 587 424 868]
 [769  70 170 884 974 778 546 249 679 572 106 891 203 949 343]
 [871 913 776 746 403 523 398 545 665 393 461 851 705 750 643]
 [356 596 349 680 537 199 481 836  62 799 468 294 928 756 513]
 [296 795 656 201 194 752 369 575 439 204 163  85  76 188 348]
 [586 853 193 730 392 354 497 606 529 153 663 836  26 809 730]]

Loweset: 9
Highest: 993


#### 9. Create a random array of size 25 and find the mean value

In [66]:
arr = random.randint(100, size=(25))
print(arr)
print(arr.mean())

[86 15 41 82 40 36 14 34  6 50 85 16 84 99 13 27 19 28 47 35 70 67 45  0
 93]
45.28


#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [68]:
arr1 = np.array([2,4,9])
arr2 = np.array([1,14,6])

10.1 What is the result of *a + b*?

In [69]:
print(arr1+arr2)

[ 3 18 15]


10.2 What is the result of *a - b*?

In [70]:
print(arr1-arr2)

[  1 -10   3]


10.3 What is the result of *a × b*?

In [71]:
print(arr1*arr2)

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [79]:
print(arr1/arr2)

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [80]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [84]:
print(arr[1, 1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [86]:
newarr = np.array(arr[1:2])
print(newarr)

[[40 50 60]]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [89]:
newarr = np.array(arr[::, 2])
print(newarr)

[30 60 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [90]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [91]:
newarr = np.array(arr[1:3, 1:3])
print(newarr)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [92]:
newarr = np.array(arr[0, ::2])
print(newarr)

[1 3]


4. Write code to reverse the order of rows in the matrix

In [93]:
print(arr[::-1])


[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


5. Write code to extract the last two columns of the matrix.

In [98]:
print(arr[::, 2:4])

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [103]:
arr1 = np.array([11, 7, 33])
arr2 = np.array([44, 5, 18])

2. Write code to join arr1 and arr2 into a single 1D array.

In [104]:
arr = np.concatenate((arr1, arr2))
print(arr)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [106]:
arr = np.vstack((arr1, arr2))
print(arr)

[[11  7 33]
 [44  5 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [107]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

5. Write code to join them horizontally (column-wise).

In [109]:
arr = np.hstack((arr1, arr2))
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [110]:
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [194]:
onedarr = np.arange(start=10, stop=29, step=2)
print(onedarr)

print('')
twodarr = random.randint(1, 50, size=(4,4))
print(twodarr)

print('')
threedarr = np.ones((2, 3, 4))
print(threedarr)

[10 12 14 16 18 20 22 24 26 28]

[[35 10 49 16]
 [24 43 36  3]
 [ 6 24  6 18]
 [29 39 13 22]]

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [195]:
newarr = onedarr.reshape(2, -1)
print(newarr)

print()
anothernewarr = twodarr[2:4, ::]
print(anothernewarr)

print()

anothertwodarr = twodarr.copy()
anothertwodarr[anothertwodarr%2==0]= -1
print(anothertwodarr)

[[10 12 14 16 18]
 [20 22 24 26 28]]

[[ 6 24  6 18]
 [29 39 13 22]]

[[35 -1 49 -1]
 [-1 43 -1  3]
 [-1 -1 -1 -1]
 [29 39 13 -1]]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [198]:
print(twodarr)
print('Mean: ', np.mean(twodarr))
print('Median: ', np.median(twodarr))
print('Standard Deviation: ', np.std(twodarr))
print()

row_sums = np.sum(twodarr, axis=1)
print(row_sums)
print()
max_value = np.max(twodarr)
max_index = np.argmax(twodarr)
print(f'Max value: {max_value} \nIndex of Max Value: {max_index}')

[[35 10 49 16]
 [24 43 36  3]
 [ 6 24  6 18]
 [29 39 13 22]]
Mean:  23.3125
Median:  23.0
Standard Deviation:  13.700906676202127

[110 106  54 103]

Max value: 49 
Index of Max Value: 2


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

In [212]:
arr = random.rand(10,10)
print(arr)
print()

minval = np.min(arr, axis=0)
print(minval)




[[0.8490462  0.67285075 0.03253747 0.77009288 0.22585037 0.40924813
  0.63359094 0.33690665 0.0236416  0.05861177]
 [0.01728196 0.85144829 0.26669892 0.36809084 0.73001231 0.28258151
  0.56936558 0.67173885 0.23170129 0.23727426]
 [0.03303521 0.01550035 0.41184944 0.14824835 0.21073481 0.09229407
  0.37483133 0.43384314 0.81385519 0.83240636]
 [0.47433486 0.53797399 0.80597448 0.43943933 0.15356186 0.79989587
  0.01188477 0.49284357 0.2322318  0.52675012]
 [0.47353477 0.26556605 0.4502151  0.89013544 0.99858293 0.38248971
  0.75685573 0.10103531 0.14596095 0.35817419]
 [0.89736648 0.85333801 0.74387481 0.02652679 0.8703923  0.75322416
  0.6421675  0.62311401 0.00472531 0.2961372 ]
 [0.22241678 0.08394942 0.41560523 0.72867468 0.19854732 0.26375033
  0.36830413 0.26768201 0.21469192 0.01696106]
 [0.27708294 0.5503777  0.12565653 0.34435887 0.83191273 0.55819138
  0.01260895 0.98433666 0.03480126 0.22352377]
 [0.6667878  0.99768033 0.46745896 0.21135578 0.38006523 0.91468628
  0.85994572